import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {applyCommand,emptyWorkspace,standings} from '../lib/workspace.ts';
import {saveCommand,readWorkspace} from '../lib/store.ts';
const act=(w,type,values={})=>applyCommand(w,{type,...values});
function squads(game='codm',count=2){let w=emptyWorkspace(game);for(let i=0;i<count;i++){w=act(w,'player.add',{tag:`Player ${i}`,uid:`uid${i}`,role:w.rules.roles[0],country:'Nigeria',age:'adult'});w=act(w,'team.add',{name:`Squad ${i}`,tier:'First team'});w=act(w,'team.assign',{teamId:w.teams.at(-1).id,playerId:w.players.at(-1).id});}return w;}
function event(w,{format='league',official=true,...rest}={}){w=act(w,'event.add',{name:'Test Cup',mode:w.rules.modes[0],season:'2026',region:'Nigeria',format,official,teamSize:1,bestOf:3,winPoints:3,placementPoints:[10,6,3,1],killPoints:2,...rest});const id=w.events.at(-1).id;for(const t of w.teams)w=act(w,'event.entry',{eventId:id,teamId:t.id});return act(w,'event.start',{eventId:id});}
const result=(w,id,scores=[2,0],kills=[])=>act(w,'match.submit',{matchId:id,scores,kills,evidence:'https://example.com/evidence',note:'Reviewed match record'});
test('game presets start empty and never inherit CODM records',()=>{const codm=squads();const val=emptyWorkspace('valorant');assert.equal(val.players.length,0);assert.equal(codm.players.length,2);assert.throws(()=>act(val,'team.assign',{teamId:codm.teams[0].id,playerId:codm.players[0].id}),/not found/);assert.throws(()=>emptyWorkspace('../../codm'),/Unknown game/);});
test('unique gamertags and game UIDs are enforced',()=>{const w=squads();assert.throws(()=>act(w,'player.add',{tag:'player 0',uid:'other',role:'OBJ',country:'Nigeria',age:'adult'}),/already exists/);assert.throws(()=>act(w,'player.add',{tag:'Other',uid:'UID0',role:'OBJ',country:'Nigeria',age:'adult'}),/already exists/);});
test('league results require valid scores, evidence and review; approved data locks',()=>{let w=event(squads());const m=w.matches[0].id,e=w.events[0].id;assert.throws(()=>result(w,m,[2,2]),/best-of/);w=act(w,'match.submit',{matchId:m,scores:[2,1],kills:[],evidence:'',note:''});assert.equal(standings(w,e)[0].points,0);assert.throws(()=>act(w,'match.approve',{matchId:m}),/evidence/);w=result(w,m,[2,1]);w=act(w,'match.dispute',{matchId:m,note:'Roster eligibility concern'});assert.throws(()=>act(w,'match.approve',{matchId:m}),/resolve/);w=result(w,m,[2,1]);w=act(w,'match.approve',{matchId:m});assert.equal(w.events[0].status,'complete');assert.equal(standings(w,e)[0].points,3);assert.throws(()=>result(w,m,[0,2]),/overwritten/);});
test('knockout advances exactly once and awards the final winner',()=>{let w=event(squads('valorant',4),{format:'knockout'});const first=[...w.matches];assert.equal(first.length,2);for(const m of first){w=result(w,m.id);w=act(w,'match.approve',{matchId:m.id});}assert.equal(w.matches.length,3);assert.throws(()=>act(w,'match.approve',{matchId:first[1].id}),/Submit/);const final=w.matches.at(-1);assert.deepEqual(final.teams,[first[0].teams[0],first[1].teams[0]]);w=result(w,final.id,[0,2]);w=act(w,'match.approve',{matchId:final.id});assert.equal(w.events[0].status,'complete');assert.equal(w.matches.at(-1).winner,first[1].teams[0]);});
test('placement rounds reject duplicate ranks and calculate points from event rules',()=>{let w=event(squads('pubg-mobile',4),{format:'placement'});const m=w.matches[0].id,e=w.events[0].id;assert.throws(()=>result(w,m,[1,1,3,4],[1,1,1,1]),/unique/);w=result(w,m,[1,2,3,4],[0,5,0,0]);w=act(w,'match.approve',{matchId:m});assert.equal(standings(w,e)[0].teamId,w.teams[1].id);assert.equal(standings(w,e)[0].points,16);w=act(w,'event.round',{eventId:e});assert.equal(w.matches[1].round,2);assert.throws(()=>act(w,'event.finish',{eventId:e}),/every round/);});
test('active roster locks and youth-transfer protections are server-side',()=>{let w=event(squads());assert.throws(()=>act(w,'team.remove',{teamId:w.teams[0].id,playerId:w.players[0].id}),/locked/);w=act(w,'transfer.add',{playerId:w.players[0].id,to:w.teams[1].id,kind:'Permanent',note:''});assert.throws(()=>act(w,'transfer.resolve',{transferId:w.transfers[0].id,accept:true,consent:true}),/locked/);let y=squads();y.players[0].age='minor';y=act(y,'transfer.add',{playerId:y.players[0].id,to:y.teams[1].id,kind:'Loan',note:''});assert.throws(()=>act(y,'transfer.resolve',{transferId:y.transfers[0].id,accept:true,consent:true}),/guardian/);});
test('approved internal roster change moves player only once',()=>{let w=squads();const p=w.players[0].id;w=act(w,'transfer.add',{playerId:p,to:w.teams[1].id,kind:'Permanent',note:''});const t=w.transfers[0].id;assert.throws(()=>act(w,'transfer.resolve',{transferId:t,accept:true,consent:false}),/consent/);w=act(w,'transfer.resolve',{transferId:t,accept:true,consent:true});assert.equal(w.teams[0].players.includes(p),false);assert.equal(w.teams[1].players.filter(x=>x===p).length,1);assert.throws(()=>act(w,'transfer.resolve',{transferId:t,accept:true,consent:true}),/resolved/);});
test('custom game rules preserve historical modes and roles',()=>{let w=emptyWorkspace('custom-00000000-0000-0000-0000-000000000001');w=act(w,'configure',{name:'New title',short:'NEW',modes:['Doubles'],roles:['Player'],rosterSize:2,resultType:'series'});assert.equal(w.rules.name,'New title');w=act(w,'player.add',{tag:'A',uid:'',role:'Player',country:'Nigeria',age:'adult'});assert.throws(()=>act(w,'configure',{name:'New title',short:'NEW',modes:['Doubles'],roles:['Striker'],rosterSize:2,resultType:'series'}),/Keep roles/);});
test('unsafe evidence URLs and empty commands fail without altering source',()=>{let w=event(squads());const before=JSON.stringify(w);assert.throws(()=>act(w,'match.submit',{matchId:w.matches[0].id,scores:[2,0],kills:[],evidence:'javascript:alert(1)',note:''}),/http/);assert.equal(JSON.stringify(w),before);assert.throws(()=>act(w,'grant.admin'),/Unknown/);});
function dbAdapter(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../drizzle/0000_public_skrulls.sql',import.meta.url),'utf8'));return {prepare(sql){return {params:[],bind(...args){this.params=args;return this;},async first(){return db.prepare(sql).get(...this.params)??null;},async all(){return {results:db.prepare(sql).all(...this.params)};},async run(){return {meta:{changes:db.prepare(sql).run(...this.params).changes}};}};}};}
test('database saves survive reload and isolate both account and game',async()=>{const db=dbAdapter();const cmd={type:'team.add',name:'NIM',tier:'First team'};await saveCommand(db,'alice','codm',0,cmd);assert.equal((await readWorkspace(db,'alice','codm')).workspace.teams[0].name,'NIM');assert.equal((await readWorkspace(db,'bob','codm')).workspace.teams.length,0);assert.equal((await readWorkspace(db,'alice','valorant')).workspace.teams.length,0);await assert.rejects(()=>saveCommand(db,'alice','codm',0,cmd),/another tab/);});
test('concurrent initial saves allow only one winner',async()=>{const db=dbAdapter();const c={type:'team.add',name:'Squad',tier:'First team'};const results=await Promise.allSettled([saveCommand(db,'alice','codm',0,c),saveCommand(db,'alice','codm',0,c)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await readWorkspace(db,'alice','codm')).workspace.teams.length,1);});
