"use client";
import {useState,useEffect,useRef,useCallback,type FormEvent,type ReactNode,type CSSProperties} from "react";
import {Gamepad2,LayoutDashboard,Users,ArrowRightLeft,Trophy,ShieldCheck,BarChart3,Medal,IdCard,Activity,BookOpen,Settings,Menu,X,Plus,Check,RefreshCw,Download,MessageSquare,ChevronRight} from "lucide-react";
import {GAMES} from "../lib/games";
import {emptyWorkspace,standings,type Workspace,type Command,type Event,type Match} from "../lib/workspace";
import {AccountChip,AuthPanel,type Account} from "./auth-panel";
import "./hub.css";
const SECTIONS=[ ["Overview",LayoutDashboard],["Club",Users],["Competition",Trophy],["Rankings",BarChart3],["Player Cards",IdCard],["Market",ArrowRightLeft],["Integrity",ShieldCheck],["Prestige",Medal],["Performance",Activity],["Map Guides",BookOpen],["Team Room",MessageSquare],["Identity",IdCard],["Settings",Settings] ] as const;
type Section=typeof SECTIONS[number][0];
type Snapshot={workspace:Workspace;version:number;updatedAt:string|null};
type Field={name:string;label:string;type?:string;options?:{value:string;label:string}[];value?:string|number;required?:boolean;min?:number;max?:number;hint?:string};
type FormSpec={title:string;fields:Field[];submit:string;command:(values:Record<string,string>)=>Command};
const options=(values:string[])=>values.map(value=>({value,label:value}));
const initials=(s:string)=>s.split(/\s+/).map(w=>w[0]).join("").slice(0,2).toUpperCase();
const date=(v:string)=>new Date(v).toLocaleString(undefined,{dateStyle:"medium",timeStyle:"short"});
function Empty({title,children,action}:{title:string;children?:ReactNode;action?:ReactNode}){return <div className="sh-empty"><h3>{title}</h3>{children&&<p>{children}</p>}{action}</div>;}
function Badge({children,tone="neutral"}:{children:ReactNode;tone?:string}){return <span className={`sh-badge ${tone}`}>{children}</span>;}
function Panel({title,action,children}:{title:string;action?:ReactNode;children:ReactNode}){return <section className="sh-panel"><header><h2>{title}</h2>{action}</header>{children}</section>;}
function FormDialog({spec,busy,onClose,onSubmit,error,onReload}:{spec:FormSpec;busy:boolean;onClose:()=>void;onSubmit:(c:Command)=>Promise<boolean>;error:string;onReload:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const before=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>before?.focus();},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;if(await onSubmit(spec.command(values)))onClose();}
 return <dialog ref={ref} className="sh-dialog" onCancel={e=>{e.preventDefault();if(!busy)onClose();}} aria-labelledby="sh-form-title"><header><h2 id="sh-form-title">{spec.title}</h2><button type="button" aria-label="Close form" disabled={busy} onClick={onClose}><X size={20}/></button></header><form onSubmit={submit}><fieldset disabled={busy}>{spec.fields.map(f=><label key={f.name}>{f.label}{f.type==="select"?<select name={f.name} defaultValue={f.value} required={f.required!==false}>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==="textarea"?<textarea name={f.name} rows={5} defaultValue={f.value} maxLength={10000} required={f.required!==false}/>:<input name={f.name} type={f.type??"text"} defaultValue={f.value} min={f.min} max={f.max} maxLength={f.type==="url"?1000:120} required={f.required!==false}/>} {f.hint&&<small>{f.hint}</small>}</label>)}</fieldset>{error&&<div className="sh-error" role="alert"><p>{error}</p><button type="button" className="sh-button" disabled={busy} onClick={onReload}>Reload latest records</button></div>}<button className="sh-primary" disabled={busy}>{busy?"Saving…":spec.submit}</button></form></dialog>;
}
export default function Hub(){
 const [game,setGame]=useState("codm"),[section,setSection]=useState<Section>("Overview"),[snap,setSnap]=useState<Snapshot>({workspace:emptyWorkspace("codm"),version:0,updatedAt:null}),[extraGames,setExtraGames]=useState<{game:string;name:string}[]>([]);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(""),[auth,setAuth]=useState(false),[notice,setNotice]=useState(""),[mobile,setMobile]=useState(false),[form,setForm]=useState<FormSpec|null>(null),[formError,setFormError]=useState("");
 const [account,setAccount]=useState<Account|null>(null);
 const [eventId,setEventId]=useState(""),[filter,setFilter]=useState(""),[rankMode,setRankMode]=useState("All modes"),[rankSeason,setRankSeason]=useState("All seasons"),[rankRegion,setRankRegion]=useState("All regions"),[teamRoom,setTeamRoom]=useState("");
 const generation=useRef(0),messageTimer=useRef<ReturnType<typeof setTimeout>|null>(null),writeLock=useRef(false);
 const w=snap.workspace;
 const teamName=(id:string)=>w.teams.find(t=>t.id===id)?.name??"Unknown squad";
 const playerName=(id:string)=>w.players.find(p=>p.id===id)?.tag??"Unknown player";
 const selectedEvent=w.events.find(e=>e.id===eventId)??w.events[0];
 const show=(message:string)=>{setNotice(message);if(messageTimer.current)clearTimeout(messageTimer.current);messageTimer.current=setTimeout(()=>setNotice(""),5000);};
 const load=useCallback(async(id:string,signal?:AbortSignal)=>{
  const turn=++generation.current;setLoading(true);setReady(false);setError("");setAuth(false);
  try{const r=await fetch(`/api/workspace?game=${encodeURIComponent(id)}`,{signal,cache:"no-store",credentials:"include"});const data=await r.json() as Snapshot & {error?:string};if(turn!==generation.current)return;if(!r.ok){setAuth(r.status===401);throw new Error(data.error??"Could not load records.");}setSnap(data);setReady(true);
  }catch(e){if(e instanceof Error&&e.name!=="AbortError"&&turn===generation.current)setError(e.message);}finally{if(turn===generation.current)setLoading(false);}
 },[]);
 useEffect(()=>{try{const id=localStorage.getItem("squadhub.game");if(id){emptyWorkspace(id);setGame(id);}}catch{}return()=>{if(messageTimer.current)clearTimeout(messageTimer.current);};},[]);
 useEffect(()=>{const ctl=new AbortController();setSnap({workspace:emptyWorkspace(game),version:0,updatedAt:null});setEventId("");setFilter("");setRankMode("All modes");setRankSeason("All seasons");setRankRegion("All regions");setTeamRoom("");load(game,ctl.signal);try{localStorage.setItem("squadhub.game",game);}catch{}return()=>ctl.abort();},[game,load]);
 useEffect(()=>{const ctl=new AbortController();fetch("/api/workspace",{signal:ctl.signal,cache:"no-store",credentials:"include"}).then(r=>r.ok?r.json() as Promise<{games:{game:string;name:string}[]}>:null).then(data=>{if(data?.games)setExtraGames(data.games);}).catch(()=>{});return()=>ctl.abort();},[]);
 useEffect(()=>{const ctl=new AbortController();fetch("/api/auth/me",{signal:ctl.signal,cache:"no-store",credentials:"include"}).then(r=>r.ok?r.json() as Promise<Account>:null).then(data=>{if(data?.id)setAccount(data);}).catch(()=>{});return()=>ctl.abort();},[]);
 async function send(command:Command){
  if(writeLock.current||!ready)return false;writeLock.current=true;setBusy(true);setFormError("");setError("");
  try{const r=await fetch("/api/workspace",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({game,version:snap.version,command})});const data=await r.json() as Snapshot & {error?:string};if(!r.ok){if(r.status===409){setReady(false);}throw new Error(data.error??"Save failed.");}setSnap(data);setExtraGames(prev=>[{game,name:data.workspace.rules.name},...prev.filter(g=>g.game!==game)]);show("Saved");return true;
  }catch(e){const message=e instanceof Error?e.message:"Save failed.";setFormError(message);setError(message);return false;}finally{writeLock.current=false;setBusy(false);}
 }
 function open(spec:FormSpec){setFormError("");setForm(spec);}
 const action=(label:string,fn:()=>void,primary=false)=><button disabled={!ready||busy} className={primary?"sh-primary":"sh-button"} onClick={fn}>{label}</button>;
 const playerOptions=w.players.map(p=>({value:p.id,label:p.tag}));
 const teamOptions=w.teams.map(t=>({value:t.id,label:t.name}));
 const modeField:Field={name:"mode",label:"Game mode",type:"select",options:options(w.rules.modes)};
 function addPlayer(){open({title:`Add ${w.rules.short} player`,submit:"Save player",fields:[{name:"tag",label:"Gamertag"},{name:"uid",label:"In-game UID",required:false,hint:"Unique within this game. Leave blank if not known."},{name:"role",label:"Role",type:"select",options:options(w.rules.roles)},{name:"country",label:"Country",value:"Nigeria"},{name:"age",label:"Age group",type:"select",options:[{value:"unknown",label:"Not confirmed"},{value:"adult",label:"18 or older"},{value:"minor",label:"Under 18"}]}],command:v=>({type:"player.add",...v})});}
 function addTeam(){open({title:"Create squad",submit:"Create squad",fields:[{name:"name",label:"Squad name"},{name:"tier",label:"Roster tier",type:"select",options:options(["First team","Second team","Academy","Ranked grinders","Community"])}],command:v=>({type:"team.add",...v})});}
 function addEvent(){open({title:"Create competition",submit:"Create competition",fields:[{name:"name",label:"Competition name"},modeField,{name:"season",label:"Season",value:"2026"},{name:"region",label:"Region",value:"Nigeria"},{name:"format",label:"Format",type:"select",value:w.rules.resultType==="placement"?"placement":"league",options:[{value:"league",label:"Round-robin league"},{value:"knockout",label:"Single elimination"},{value:"placement",label:"Battle royale / placement rounds"}]},{name:"official",label:"Record category",type:"select",options:[{value:"false",label:"Practice / scrim"},{value:"true",label:"Official competition"}],hint:"Practice never contributes to official rankings."},{name:"teamSize",label:"Minimum starting roster",type:"number",min:1,max:20,value:w.rules.rosterSize,hint:"Set this per event: 1 for solo, 2 for duos, etc."},{name:"bestOf",label:"Best of (series formats)",type:"select",value:"3",options:options(["1","3","5","7","9"])},{name:"winPoints",label:"Points per series win",type:"number",min:1,max:10,value:3},{name:"placementPoints",label:"Placement points, highest first",value:"15,12,10,8,6,4,2,1",hint:"For placement rounds. Unlisted places receive zero."},{name:"killPoints",label:"Points per elimination",type:"number",min:0,max:100,value:1}],command:v=>({type:"event.add",...v,official:v.official==="true",teamSize:Number(v.teamSize),bestOf:Number(v.bestOf),winPoints:Number(v.winPoints),placementPoints:v.placementPoints.split(",").map(Number),killPoints:Number(v.killPoints)})});}
 function submitResult(m:Match,e:Event){open({title:m.status==="disputed"?"Resolve disputed result":"Submit result",submit:"Save for review",fields:[...m.teams.flatMap((id,i):Field[]=>[{name:`score${i}`,label:`${teamName(id)}: ${e.format==="placement"?"placement":"series wins"}`,type:"number",min:e.format==="placement"?1:0,max:e.format==="placement"?m.teams.length:e.bestOf,value:m.scores[i]??(e.format==="placement"?i+1:0)},...(e.format==="placement"?[{name:`kills${i}`,label:`${teamName(id)}: eliminations`,type:"number",min:0,max:500,value:m.kills[i]??0}]:[])]),{name:"evidence",label:"Result evidence URL",type:"url",value:m.evidence,required:false,hint:"Required before approval. Use a screenshot or match record link."},{name:"note",label:"Result / resolution notes",type:"textarea",value:m.note,required:false}],command:v=>({type:"match.submit",matchId:m.id,scores:m.teams.map((_,i)=>Number(v[`score${i}`])),kills:m.teams.map((_,i)=>Number(v[`kills${i}`])),evidence:v.evidence,note:v.note})});}
 function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),...snap},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`squadhub-${game}-records.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function exportCard(playerId:string){const p=w.players.find(p=>p.id===playerId)!;const squad=w.teams.find(t=>t.players.includes(p.id));const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]!));const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="760" viewBox="0 0 600 760"><rect width="600" height="760" rx="32" fill="#10151b"/><rect x="40" y="40" width="520" height="8" fill="${w.rules.color}"/><g fill="#eef3f5" font-family="Arial,sans-serif"><text x="48" y="108" font-size="24">SQUADHUB · ${esc(w.rules.short)}</text><text x="48" y="280" font-size="100" fill="${w.rules.color}">${esc(initials(p.tag))}</text><text x="48" y="380" font-size="30">${esc(p.tag.slice(0,25))}</text><text x="48" y="436" font-size="22">${esc(p.role)} · ${esc(p.country)}</text><text x="48" y="498" font-size="22">${esc((squad?.name??"Free agent").slice(0,35))}</text><text x="48" y="650" font-size="18" fill="#b8c3cb">Manager-entered player passport</text><text x="48" y="688" font-size="18" fill="#b8c3cb">No publisher verification or invented rating</text></g></svg>`;const url=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));const a=document.createElement("a");a.href=url;a.download=`squadhub-player-${p.id}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function table(e:Event){const rows=standings(w,e.id);return <div className="sh-table-wrap"><table><caption>{e.name} · {e.mode} · {e.region} · {e.season}</caption><thead><tr><th scope="col">Squad</th><th scope="col">Played</th><th scope="col">Wins</th><th scope="col">{e.format==="placement"?"Eliminations":"Map diff."}</th><th scope="col">Points</th></tr></thead><tbody>{rows.map(row=><tr key={row.teamId}><th scope="row">{teamName(row.teamId)}</th><td>{row.played}</td><td>{row.wins}</td><td>{row.difference}</td><td><b>{row.points}</b></td></tr>)}</tbody></table>{!rows.length&&<Empty title="No entrants yet"/>}<p className="sh-method">Only approved results count. {e.format==="placement"?`Placement points: ${e.placementPoints.join(", ")}. Each elimination: ${e.killPoints} points. Ties: wins, then eliminations.`:`${e.winPoints} points per win. Ties: wins, then map difference.`} Equal records remain tied; display order is stable.</p></div>;}
 function matchCard(m:Match){const e=w.events.find(e=>e.id===m.eventId)!;return <article className="sh-match" key={m.id}><div className="sh-row"><small>{e.name} · Round {m.round}</small><Badge tone={m.status==="approved"?"good":m.status==="disputed"?"bad":"neutral"}>{m.status}</Badge></div><h3>{e.format==="placement"?`${m.teams.length} squads · placement round`:m.teams.map(teamName).join(" vs ")}</h3>{m.scores.length>0&&<p>{m.teams.map((id,i)=>`${teamName(id)} ${e.format==="placement"?"#":""}${m.scores[i]}${e.format==="placement"?` (${m.kills[i]} eliminations)`:""}`).join(" · ")}</p>}{m.note&&<p>{m.note}</p>}{m.evidence&&<a href={m.evidence} target="_blank" rel="noopener noreferrer">View evidence ↗</a>}<div className="sh-actions">{m.status!=="approved"&&action(m.status==="disputed"?"Resolve result":"Enter result",()=>submitResult(m,e))}{m.status==="submitted"&&<>{action("Approve",()=>send({type:"match.approve",matchId:m.id}))}{action("Dispute",()=>open({title:"Dispute result",submit:"Record dispute",fields:[{name:"note",label:"Reason",type:"textarea"}],command:v=>({type:"match.dispute",matchId:m.id,note:v.note})}))}</>}</div></article>;}
 const cleanFilter=filter.trim().toLowerCase();
 const visiblePlayers=w.players.filter(p=>[p.tag,p.role,p.country].some(v=>v.toLowerCase().includes(cleanFilter)));
 const catalog=[...GAMES.map(g=>({game:g.id,name:extraGames.find(e=>e.game===g.id)?.name??g.name})),...extraGames.filter(g=>!GAMES.some(x=>x.id===g.game))];if(!catalog.some(g=>g.game===game))catalog.push({game,name:w.rules.name});
 const approved=w.matches.filter(m=>m.status==="approved");
 return <main className="sh-app" style={{"--sh-game-color":w.rules.color} as CSSProperties}><a className="sh-skip" href="#sh-content">Skip to content</a><aside className={`sh-sidebar ${mobile?"is-open":""}`}><div className="sh-brand"><span><Gamepad2 size={24}/></span><strong>SquadHub</strong><button aria-label="Close navigation" className="sh-mobile" onClick={()=>setMobile(false)}><X size={22}/></button></div><div className="sh-game-label">COMPETITION HQ</div><label className="sh-game">Game<select value={game} disabled={busy||!!form} onChange={e=>setGame(e.target.value)}>{catalog.map(g=><option key={g.game} value={g.game}>{g.name}</option>)}</select></label><nav aria-label="Primary navigation">{SECTIONS.map(([name,Icon])=><button key={name} aria-current={section===name?"page":undefined} className={section===name?"selected":""} onClick={()=>{setSection(name);setMobile(false);setFilter("");}}><Icon size={18}/><span>{name}</span>{name==="Integrity"&&w.matches.some(m=>m.status==="disputed")&&<b>{w.matches.filter(m=>m.status==="disputed").length}</b>}</button>)}</nav><footer><span>Private organizer workspace</span><a href="/demo">Prototype archive ↗</a></footer></aside>{mobile&&<button className="sh-backdrop" aria-label="Close navigation" onClick={()=>setMobile(false)}/>}
 <div className="sh-main"><header className="sh-top"><button className="sh-mobile" aria-label="Open navigation" onClick={()=>setMobile(true)}><Menu size={22}/></button><div><span className="sh-game-chip">{w.rules.short}</span><span className="sh-breadcrumb">Workspace <ChevronRight size={14}/> {section}</span></div><div className="sh-actions"><AccountChip account={account} onSignedOut={()=>{setAccount(null);setAuth(true);setReady(false);setError("Sign in to load your saved workspace.");}}/><button className="sh-button" disabled={busy||loading} onClick={()=>load(game)} aria-label="Reload saved records"><RefreshCw size={16}/><span>Refresh</span></button></div></header>
 <div className="sh-content" id="sh-content"><div className="sh-heading"><div><p>{w.rules.name}</p><h1>{section==="Overview"?"Command center":section}</h1></div><div className="sh-actions">{["Club","Player Cards","Identity"].includes(section)&&action("Add player",addPlayer,true)}{section==="Club"&&action("Create squad",addTeam)}{section==="Competition"&&action("Create competition",addEvent,true)}{section==="Settings"&&<button className="sh-button" disabled={!ready} onClick={exportData}><Download size={16}/> Export records</button>}</div></div>
 {error&&!auth&&<div className="sh-error" role="alert"><p>{error}</p><button className="sh-button" disabled={loading||busy} onClick={()=>load(game)}>Reload records</button></div>}
 {auth&&!ready&&<AuthPanel onSignedIn={account=>{setAccount(account);setAuth(false);load(game);}}/>}
 {loading?<div className="sh-skeletons" role="status" aria-label="Loading game records">{[1,2,3,4].map(i=><div key={i}/>)}<span className="sh-sr">Loading game records…</span></div>:!ready&&!auth?<Empty title="Saved workspace unavailable">Your game records will appear here once the connection is restored.</Empty>:!ready?null:<>
 {section==="Overview"&&<><div className="sh-stats">{[[w.teams.length,"Squads"],[w.players.length,"Players"],[w.events.filter(e=>e.status==="running").length,"Running events"],[approved.length,"Approved results"]].map(([n,label])=><div key={label}><strong>{n}</strong><span>{label}</span></div>)}</div><div className="sh-columns"><Panel title="Next up" action={action("Create competition",addEvent)}>{w.matches.filter(m=>m.status!=="approved").slice(0,3).map(matchCard)}{!w.matches.some(m=>m.status!=="approved")&&<Empty title={w.events.length?"All caught up":"Build your first competition"}>{w.teams.length?"Create an event, register squads and generate the fixtures.":"Add players and squads first. Each game starts with its own clean records."}<br/>{action("Create squad",addTeam,true)}</Empty>}</Panel><Panel title="Club setup"><ol className="sh-checklist">{[[w.players.length>0,"Add player passports",()=>setSection("Identity")],[w.teams.length>0,"Build your squads",()=>setSection("Club")],[w.events.length>0,"Set competition rules",()=>setSection("Competition")],[approved.length>0,"Review match evidence",()=>setSection("Integrity")]].map(([done,label,fn])=><li key={String(label)}><span>{done?<Check size={16}/>:"○"}</span><button onClick={fn as ()=>void}>{label as string}</button></li>)}</ol><p className="sh-method">Records belong to {w.rules.name}. Changing games does not move players, results or rankings.</p></Panel></div><Panel title="Recent activity">{w.audit.length?w.audit.slice(0,6).map(a=><div className="sh-list-row" key={a.id}><span>{a.action.replaceAll("."," · ")}</span><time>{date(a.at)}</time></div>):<Empty title="No recorded activity yet"/>}</Panel></>}
 {section==="Club"&&<><div className="sh-grid">{w.teams.map(t=><Panel key={t.id} title={t.name} action={<Badge>{t.tier}</Badge>}><div className="sh-roster">{t.players.map(id=>{const p=w.players.find(p=>p.id===id)!;return <div className="sh-list-row" key={id}><span className="sh-avatar">{initials(p.tag)}</span><div><b>{p.tag}</b><small>{p.role}</small></div>{action("Remove",()=>send({type:"team.remove",teamId:t.id,playerId:id}))}</div>;})}{!t.players.length&&<Empty title="Roster is empty"/>}</div>{action("Assign player",()=>open({title:`Add to ${t.name}`,submit:"Assign player",fields:[{name:"playerId",label:"Unassigned player",type:"select",options:playerOptions.filter(p=>!w.teams.some(t=>t.players.includes(p.value)))}],command:v=>({type:"team.assign",teamId:t.id,playerId:v.playerId})}))}</Panel>)}</div>{!w.teams.length&&<Empty title="No squads for this game" action={action("Create squad",addTeam,true)}>Create first-team, academy, community or ranked-grinder rosters.</Empty>}</>}
 {section==="Competition"&&<>{w.events.length?<><div className="sh-filterbar"><label>Competition<select value={selectedEvent?.id} onChange={e=>setEventId(e.target.value)}>{w.events.map(e=><option key={e.id} value={e.id}>{e.name} · {e.season}</option>)}</select></label><Badge tone={selectedEvent?.official?"good":"neutral"}>{selectedEvent?.official?"Official":"Practice"}</Badge><Badge>{selectedEvent?.status}</Badge></div>{selectedEvent&&<><div className="sh-event-info"><span>{selectedEvent.mode}</span><span>{selectedEvent.region} · {selectedEvent.season}</span><span>{selectedEvent.teamSize} starting players</span><span>{selectedEvent.format==="placement"?"Placement rounds":`${selectedEvent.format==="league"?"League":"Single elimination"} · Best of ${selectedEvent.bestOf}`}</span></div>{selectedEvent.status==="registration"&&<Panel title="Registered squads" action={action("Register squad",()=>open({title:"Register squad",submit:"Register",fields:[{name:"teamId",label:"Squad",type:"select",options:teamOptions.filter(t=>!selectedEvent.teams.includes(t.value))}],command:v=>({type:"event.entry",eventId:selectedEvent.id,teamId:v.teamId})}))}>{selectedEvent.teams.map(id=><div className="sh-list-row" key={id}><b>{teamName(id)}</b><span>{w.teams.find(t=>t.id===id)?.players.length} players</span></div>)}{!selectedEvent.teams.length&&<Empty title="Registration is open">Register at least two squads. Solo competitions use one-player squads.</Empty>}{action("Lock rosters & generate fixtures",()=>send({type:"event.start",eventId:selectedEvent.id}),true)}</Panel>}<div className="sh-grid">{w.matches.filter(m=>m.eventId===selectedEvent.id).map(matchCard)}</div>{selectedEvent.format==="placement"&&selectedEvent.status==="running"&&<div className="sh-actions">{action("Add next round",()=>send({type:"event.round",eventId:selectedEvent.id}))}{action("Close competition",()=>send({type:"event.finish",eventId:selectedEvent.id}))}</div>}{selectedEvent.status!=="registration"&&<Panel title="Competition table">{table(selectedEvent)}</Panel>}</>}</>:<Empty title="No competitions yet" action={action("Create competition",addEvent,true)}>Choose league, knockout or placement scoring. Event rules can differ from the game's defaults.</Empty>}</>}
 {section==="Rankings"&&<><div className="sh-filterbar"><label>Mode<select value={rankMode} onChange={e=>setRankMode(e.target.value)}>{options(["All modes",...w.rules.modes]).map(o=><option key={o.value}>{o.label}</option>)}</select></label><label>Season<select value={rankSeason} onChange={e=>setRankSeason(e.target.value)}>{["All seasons",...new Set(w.events.map(e=>e.season))].map(x=><option key={x}>{x}</option>)}</select></label><label>Region<select value={rankRegion} onChange={e=>setRankRegion(e.target.value)}>{["All regions",...new Set(w.events.map(e=>e.region))].map(x=><option key={x}>{x}</option>)}</select></label></div>{w.events.filter(e=>e.official&&(rankMode==="All modes"||e.mode===rankMode)&&(rankSeason==="All seasons"||e.season===rankSeason)&&(rankRegion==="All regions"||e.region===rankRegion)).map(e=><Panel key={e.id} title={e.name}>{table(e)}</Panel>)}{!w.events.some(e=>e.official&&(rankMode==="All modes"||e.mode===rankMode)&&(rankSeason==="All seasons"||e.season===rankSeason)&&(rankRegion==="All regions"||e.region===rankRegion))&&<Empty title="No official competitions match">Practice results are kept out of official tables. Different formats and seasons retain separate tables.</Empty>}</>}
 {["Player Cards","Identity"].includes(section)&&<><div className="sh-filterbar"><label>Find a player<input type="search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Gamertag, role or country"/></label></div><div className="sh-player-grid">{visiblePlayers.map(p=><article className="sh-player" key={p.id}><div className="sh-row"><span>{w.rules.short}</span><Badge>Manager-entered</Badge></div><div className="sh-player-initials">{initials(p.tag)}</div><h2>{p.tag}</h2><p>{p.role} · {p.country}</p><dl><div><dt>Squad</dt><dd>{w.teams.find(t=>t.players.includes(p.id))?.name??"Free agent"}</dd></div><div><dt>Game UID</dt><dd>{p.uid||"Not supplied"}</dd></div><div><dt>Age group</dt><dd>{p.age==="adult"?"18+":p.age==="minor"?"Under 18":"Unconfirmed"}</dd></div></dl><button className="sh-button" onClick={()=>exportCard(p.id)}><Download size={16}/> Export player card</button></article>)}</div>{!visiblePlayers.length&&<Empty title={w.players.length?"No players match":"No player passports yet"} action={action("Add player",addPlayer,true)}/>}<p className="sh-method">These are organizer-maintained records. Phone verification, guardian approval and publisher identity checks are not connected. Player ratings are not fabricated.</p></>}
 {section==="Market"&&<><div className="sh-toolbar">{action("Propose roster move",()=>open({title:"Propose roster move",submit:"Save proposal",fields:[{name:"playerId",label:"Player",type:"select",options:playerOptions.filter(p=>w.teams.some(t=>t.players.includes(p.value)))},{name:"to",label:"Destination squad",type:"select",options:teamOptions},{name:"kind",label:"Type",type:"select",options:options(["Permanent","Loan"])},{name:"note",label:"Terms / return date for loans",type:"textarea",required:false}],command:v=>({type:"transfer.add",...v})}),true)}</div><Panel title="Transfer register">{w.transfers.map(t=><article className="sh-match" key={t.id}><div className="sh-row"><h3>{playerName(t.playerId)}</h3><Badge>{t.status}</Badge></div><p>{teamName(t.from)} → {teamName(t.to)} · {t.kind}</p>{t.note&&<p>{t.note}</p>}{t.status==="proposed"&&<div className="sh-actions">{action("Record consent & complete",()=>open({title:"Confirm roster move",submit:"Complete roster move",fields:[{name:"consent",label:"Player's consent",type:"select",options:[{value:"no",label:"Not received"},{value:"yes",label:"Received and recorded by me"}],hint:"This is an internal roster record, not a signed contract or payment."}],command:v=>({type:"transfer.resolve",transferId:t.id,accept:true,consent:v.consent==="yes"})}))}{action("Reject",()=>send({type:"transfer.resolve",transferId:t.id,accept:false}))}</div>}</article>)}{!w.transfers.length&&<Empty title="No transfer proposals"/>}</Panel><p className="sh-method">Active-event rosters are locked. Transfers involving minors or unconfirmed ages are blocked. Loans are recorded manually; return dates do not trigger automatic roster changes. Payments and signed contracts are not connected.</p></>}
 {section==="Integrity"&&<><p className="sh-method">You review results as this workspace's organizer. Approval requires an evidence link and locks the result. It is not publisher verification.</p><div className="sh-grid">{w.matches.filter(m=>["submitted","disputed"].includes(m.status)).map(matchCard)}</div>{!w.matches.some(m=>["submitted","disputed"].includes(m.status))&&<Empty title="No results awaiting review"/>}<Panel title="Activity log">{w.audit.map(a=><div className="sh-list-row" key={a.id}><span>{a.action.replaceAll("."," · ")}</span><time>{date(a.at)}</time></div>)}{!w.audit.length&&<Empty title="No changes recorded"/>}<p className="sh-method">Most recent 250 actions. Approved results remain in the competition record.</p></Panel></>}
 {section==="Prestige"&&<><div className="sh-grid">{w.events.filter(e=>e.official&&e.status==="complete").map(e=>{const rows=standings(w,e.id),final=w.matches.filter(m=>m.eventId===e.id).sort((a,b)=>b.round-a.round)[0];const champion=e.format==="knockout"?final?.winner:rows[0]?.teamId;const tied=e.format!=="knockout"&&rows.length>1&&rows[0].points===rows[1].points&&rows[0].wins===rows[1].wins&&rows[0].difference===rows[1].difference;return <article className="sh-trophy" key={e.id}><Trophy size={32}/><span>{e.season} · {e.mode}</span><h2>{e.name}</h2><strong>{tied?"Joint leading record":champion?teamName(champion):"No winner"}</strong><p>{tied?"A tiebreak is required before naming one champion.":"Competition winner"}</p></article>;})}</div>{!w.events.some(e=>e.official&&e.status==="complete")&&<Empty title="The trophy cabinet starts here">Complete an official competition with approved results to establish a winner.</Empty>}</>}
 {section==="Performance"&&<><div className="sh-stats"><div><strong>{approved.length}</strong><span>Reviewed results</span></div><div><strong>{w.tasks.filter(t=>t.done).length}/{w.tasks.length}</strong><span>Drills completed</span></div><div><strong>{w.matches.filter(m=>m.status==="disputed").length}</strong><span>Disputed results</span></div></div><Panel title="Training plan" action={action("Add drill",()=>open({title:"Add training drill",submit:"Save drill",fields:[{name:"title",label:"Drill title"},modeField,{name:"notes",label:"Goal, steps and evidence",type:"textarea",required:false}],command:v=>({type:"task.add",...v})}))}>{w.tasks.map(t=><div className="sh-task" key={t.id}><input type="checkbox" aria-label={`Complete ${t.title}`} checked={t.done} disabled={busy} onChange={()=>send({type:"task.toggle",taskId:t.id})}/><div><h3>{t.title}</h3><small>{t.mode}</small><p>{t.notes}</p></div><Badge tone={t.done?"good":"neutral"}>{t.done?"Complete":"Planned"}</Badge></div>)}{!w.tasks.length&&<Empty title="No drills planned yet">Build a training plan from your match reviews.</Empty>}</Panel><Panel title="Squad performance">{w.teams.map(t=>{const ms=approved.filter(m=>m.teams.includes(t.id));const wins=ms.filter(m=>m.winner===t.id).length;return <div className="sh-list-row" key={t.id}><b>{t.name}</b><span>{ms.length?`${wins}/${ms.length} wins · ${Math.round(wins/ms.length*100)}%`:"No approved results"}</span></div>;})}<p className="sh-method">Includes this game's approved practice and official results. A placement-round win means first place. AI VOD analysis and automated weekly reviews require an AI service; this workspace does not simulate them.</p></Panel></>}
 {section==="Map Guides"&&<><div className="sh-toolbar">{action("Add guide",()=>open({title:"Add map or strategy guide",submit:"Save guide",fields:[{name:"title",label:"Map / strategy name"},modeField,{name:"notes",label:"Callouts, roles and plan",type:"textarea"},{name:"url",label:"Source / VOD URL",type:"url",required:false}],command:v=>({type:"guide.add",...v})}),true)}</div><div className="sh-grid">{w.guides.map(g=><Panel key={g.id} title={g.title} action={<Badge>{g.mode}</Badge>}><p className="sh-prose">{g.notes}</p>{g.url&&<a href={g.url} target="_blank" rel="noopener noreferrer">Open source ↗</a>}<p className="sh-method">Saved {date(g.updatedAt)}</p></Panel>)}</div>{!w.guides.length&&<Empty title="Your playbook is empty">Save game-specific map callouts, rotations or match plans with source links.</Empty>}</>}
 {section==="Team Room"&&<Panel title="Squad notes">{w.teams.length?<><label className="sh-field">Squad<select value={teamRoom||w.teams[0].id} onChange={e=>setTeamRoom(e.target.value)}>{teamOptions.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>{w.room.filter(n=>n.teamId===(teamRoom||w.teams[0].id)).map(n=><div className="sh-note" key={n.id}><p>{n.text}</p><time>{date(n.at)}</time></div>)}<form className="sh-room-form" onSubmit={async e=>{e.preventDefault();const f=e.currentTarget;const text=String(new FormData(f).get("text")??"");if(await send({type:"room.add",teamId:teamRoom||w.teams[0].id,text}))f.reset();}}><label>New note<textarea name="text" required maxLength={2000} rows={3}/></label><button className="sh-primary" disabled={busy}>Save note</button></form><p className="sh-method">Private notes for this organizer account. Shared chat, invitations and WebSocket delivery are not connected.</p></>:<Empty title="Create a squad first"/>}</Panel>}
 {section==="Settings"&&<><Panel title="Game rules" action={action("Edit game rules",()=>open({title:"Configure game",submit:"Save rules",fields:[{name:"name",label:"Game name",value:w.rules.name},{name:"short",label:"Short name",value:w.rules.short},{name:"modes",label:"Modes, separated by commas",value:w.rules.modes.join(", ")},{name:"roles",label:"Player roles, separated by commas",value:w.rules.roles.join(", ")},{name:"rosterSize",label:"Default starting roster",type:"number",min:1,max:20,value:w.rules.rosterSize},{name:"resultType",label:"Default result format",type:"select",value:w.rules.resultType,options:[{value:"series",label:"Head-to-head series"},{value:"placement",label:"Placement / battle royale"}]}],command:v=>({type:"configure",...v,modes:v.modes.split(",").map(s=>s.trim()),roles:v.roles.split(",").map(s=>s.trim()),rosterSize:Number(v.rosterSize)})}))}><dl className="sh-settings"><div><dt>Game</dt><dd>{w.rules.name}</dd></div><div><dt>Modes</dt><dd>{w.rules.modes.join(", ")}</dd></div><div><dt>Roles</dt><dd>{w.rules.roles.join(", ")}</dd></div><div><dt>Starting roster</dt><dd>{w.rules.rosterSize}</dd></div></dl><p className="sh-method">Presets are editable planning templates. Set current tournament rules on each event. Editing defaults does not rewrite existing events.</p></Panel><Panel title="Add another esports game"><p>Use a custom game for any title outside the built-in list.</p><button className="sh-primary" disabled={busy} onClick={()=>{setGame(`custom-${crypto.randomUUID()}`);setSection("Settings");}}>Add custom game</button><p className="sh-method">Name it and save its rules to keep it in your game selector.</p></Panel><Panel title="Connection status"><div className="sh-list-row"><span>Saved game records</span><Badge tone="good">Connected</Badge></div><div className="sh-list-row"><span>Account access</span><span>{account?.method==="session"?"Organizer session cookie":"ChatGPT sign-in or email/password on Vercel"}</span></div>{["Public player accounts & SMS verification","Guardian verification & contracts","Payments & premium subscriptions","AI video reviews & scheduled jobs","Shared team chat & WebSockets","Public CRA blacklist & appeals"].map(label=><div className="sh-list-row" key={label}><span>{label}</span><Badge>Not connected</Badge></div>)}<p className="sh-method">This is a private organizer workspace. The archived demo remains available to reference the planned public platform.</p></Panel></>}
 <footer className="sh-bottom"><span>{snap.updatedAt?`Saved ${date(snap.updatedAt)}`:"No records saved yet"}</span><span>{w.rules.short} · Organizer records</span></footer></>}
 </div></div>{form&&<FormDialog spec={form} busy={busy} error={formError} onClose={()=>setForm(null)} onSubmit={send} onReload={()=>load(game)}/>} {notice&&<div className="sh-toast" role="status"><Check size={18}/>{notice}</div>}</main>;
}
