import React,{useState} from 'react';
import { ScrollView,View,Text,StyleSheet,Pressable } from 'react-native';
import { colors } from '../theme/colors';
import { SectionHeader,Pill,Metric,Card } from '../components/UI';
import { DetailRoute } from '../types/navigation';
import { playerHistory } from '../data/appData';
export function CareerScreen({open}:{open:(r:DetailRoute)=>void}){const[tab,setTab]=useState<'OVERVIEW'|'HISTORY'|'STATS'|'TROPHIES'>('OVERVIEW');return <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
<Pressable onPress={()=>open('PLAYER_PASSPORT')} style={s.passport}><View style={s.top}><View style={s.avatar}><Text style={s.avatarText}>G</Text></View><View style={{flex:1}}><View style={s.nameRow}><Text style={s.name}>N¡M・GOJO</Text><Text style={s.verified}>✓</Text></View><Text style={s.role}>SUPPORT / OBJ • MULTIPLAYER</Text><Text style={s.shid}>SH-000128 • NIGERIA • WEST AFRICA</Text></View><Pill text="T1"/></View><View style={s.divider}/><View style={s.metrics}><Metric value="#12" label="AFRICA MP" accent/><Metric value="1,742" label="RATING"/><Metric value="₦185K" label="VALUE"/><Metric value="94" label="TRUST"/></View><Text style={s.open}>OPEN FULL PLAYER PASSPORT  →</Text></Pressable>
<View style={s.tabs}>{(['OVERVIEW','HISTORY','STATS','TROPHIES'] as const).map(t=><Pressable key={t} onPress={()=>setTab(t)} style={[s.tab,tab===t&&s.tabOn]}><Text style={[s.tabT,tab===t&&s.tabTOn]}>{t}</Text></Pressable>)}</View>
{tab==='OVERVIEW'?<><SectionHeader title="CURRENT TEAM"/><Card><View style={s.teamRow}><View style={s.teamLogo}><Text style={s.teamLogoT}>N</Text></View><View style={{flex:1}}><Text style={s.teamName}>NIM ESPORTS</Text><Text style={s.teamSub}>FIRST TEAM • T1 COMPETITIVE • NIGERIA</Text></View><Text style={s.chev}>›</Text></View></Card><SectionHeader title="RECENT FORM"/><Card accent><View style={s.formRow}><Text style={s.formScore}>8.7</Text><View style={{flex:1}}><Text style={s.formTitle}>STRONG FORM</Text><Text style={s.formCopy}>Objective impact, assist efficiency and hill time are above your 30-day average.</Text></View><Pressable onPress={()=>open('PERFORMANCE')}><Text style={s.ai}>AI REVIEW →</Text></Pressable></View></Card></>:null}
{tab==='HISTORY'?<>{playerHistory.map((e,i)=><View style={s.timeline} key={i}><View style={s.dotCol}><View style={s.dot}/>{i<playerHistory.length-1?<View style={s.line}/>:null}</View><View style={{flex:1,paddingBottom:18}}><Text style={s.date}>{e.date}</Text><Text style={s.histTitle}>{e.title}</Text><Text style={s.histDetail}>{e.detail}</Text></View></View>)}</>:null}
{tab==='STATS'?<View style={s.statGrid}>{[['1.28','K/D'],['74%','OBJ WIN'],['62%','MAP WIN'],['8.7','FORM'],['23.4s','AVG HILL'],['91','TEAM IMPACT']].map(([v,l])=><View key={l} style={s.statTile}><Text style={s.statV}>{v}</Text><Text style={s.statL}>{l}</Text></View>)}</View>:null}
{tab==='TROPHIES'?<><SectionHeader title="TROPHY CABINET"/><View style={s.trophyGrid}>{[['🏆','AER WEEKLY 31','CHAMPION'],['★','AER WEEKLY 31','MVP'],['🥈','WA MASTERS','RUNNER-UP'],['🎯','MONTHLY AWARD','BEST OBJ']].map(([i,t,sub])=><View key={t+sub} style={s.trophy}><Text style={s.trophyIcon}>{i}</Text><Text style={s.trophyTitle}>{t}</Text><Text style={s.trophySub}>{sub}</Text></View>)}</View></>:null}
</ScrollView>}
const s=StyleSheet.create({content:{padding:16,paddingBottom:32},passport:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:10,padding:16},top:{flexDirection:'row',alignItems:'center',gap:11},avatar:{width:56,height:56,borderRadius:9,backgroundColor:colors.red,alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontSize:23,fontWeight:'700'},nameRow:{flexDirection:'row',alignItems:'center',gap:5},name:{color:colors.white,fontSize:17,fontWeight:'700'},verified:{color:'#fff',backgroundColor:colors.red,width:16,height:16,borderRadius:8,textAlign:'center',fontSize:10,fontWeight:'700'},role:{color:colors.muted,fontSize:8,fontWeight:'600',marginTop:4},shid:{color:colors.subtle,fontSize:8,fontWeight:'600',marginTop:4},divider:{height:1,backgroundColor:'#331014',marginVertical:14},metrics:{flexDirection:'row'},open:{color:colors.redBright,fontSize:8,fontWeight:'700',marginTop:14},tabs:{flexDirection:'row',borderBottomWidth:1,borderBottomColor:colors.border,marginVertical:18},tab:{flex:1,alignItems:'center',paddingBottom:10},tabOn:{borderBottomWidth:2,borderBottomColor:colors.red},tabT:{color:colors.muted,fontSize:8,fontWeight:'600'},tabTOn:{color:colors.white},teamRow:{flexDirection:'row',alignItems:'center',gap:10},teamLogo:{width:42,height:42,borderRadius:10,backgroundColor:colors.surface3,alignItems:'center',justifyContent:'center'},teamLogoT:{color:colors.redBright,fontSize:17,fontWeight:'700'},teamName:{color:colors.white,fontSize:11,fontWeight:'700'},teamSub:{color:colors.muted,fontSize:8,marginTop:3},chev:{color:colors.redBright,fontSize:24},formRow:{flexDirection:'row',alignItems:'center',gap:11},formScore:{color:colors.success,fontSize:27,fontWeight:'700'},formTitle:{color:colors.white,fontSize:10,fontWeight:'700'},formCopy:{color:colors.muted,fontSize:8,lineHeight:12,marginTop:3},ai:{color:colors.redBright,fontSize:8,fontWeight:'700'},timeline:{flexDirection:'row'},dotCol:{width:24,alignItems:'center'},dot:{width:9,height:9,borderRadius:9,backgroundColor:colors.red,marginTop:3},line:{width:1,backgroundColor:'#3D1418',flex:1,marginTop:3},date:{color:colors.subtle,fontSize:8,fontWeight:'600'},histTitle:{color:colors.white,fontSize:11,fontWeight:'700',marginTop:4},histDetail:{color:colors.muted,fontSize:9,marginTop:3},statGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},statTile:{width:'31%',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:8,padding:13},statV:{color:colors.white,fontSize:19,fontWeight:'700'},statL:{color:colors.subtle,fontSize:7,fontWeight:'600',marginTop:3},trophyGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},trophy:{width:'48.5%',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:9,padding:14,minHeight:120},trophyIcon:{fontSize:26},trophyTitle:{color:colors.white,fontSize:10,fontWeight:'700',marginTop:10},trophySub:{color:colors.redBright,fontSize:8,fontWeight:'600',marginTop:3}});
