import React,{useEffect,useState} from 'react';
import { ScrollView,View,Text,StyleSheet,Pressable } from 'react-native';
import { colors } from '../theme/colors';
import { SectionHeader,Pill,Metric,Card,ActionButton } from '../components/UI';
import { DetailRoute } from '../types/navigation';
import { rankings,tournaments as demoTournaments } from '../data/appData';
import { platformApi,RankingRow,Tournament } from '../services/api';

type SyncState='loading'|'live'|'fallback';

export function CompeteScreen({open}:{open:(r:DetailRoute)=>void}){
const[mode,setMode]=useState<'MP'|'BR'>('MP');
const[liveEvents,setLiveEvents]=useState<Tournament[]|null>(null);
const[liveRanks,setLiveRanks]=useState<RankingRow[]|null>(null);
const[syncState,setSyncState]=useState<SyncState>('loading');
const data=rankings[mode];
useEffect(()=>{let active=true;setSyncState('loading');
const load=async()=>{try{const[events,seasons]=await Promise.all([platformApi.tournaments.list(mode),platformApi.rankings.seasons()]);const season=seasons.find(row=>row.is_active)??seasons[0];const table=season?await platformApi.rankings.table(season.id,mode):[];if(active){setLiveEvents(events);setLiveRanks(table);setSyncState('live')}}catch{if(active){setLiveEvents(null);setLiveRanks(null);setSyncState('fallback')}}};
void load();return()=>{active=false}},[mode]);
const top=liveRanks?.[0];
const cards=liveEvents===null?demoTournaments.filter(t=>t.mode===mode):liveEvents.map(t=>({id:t.id,tier:t.tier.toUpperCase(),status:t.status.toUpperCase(),date:new Date(t.starts_at).toLocaleDateString(),name:t.name,organizer:'Verified organizer',teams:t.max_teams,weight:t.ranking_weight,prize:t.prize_pool_naira?`₦${t.prize_pool_naira.toLocaleString()}`:'Community prize'}));
return <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
<Text style={s.title}>Competition</Text><Text style={s.copy}>Every verified tournament feeds the same official ledger. Rankings are calculated centrally, not declared by organizers.</Text>
<View style={s.modeSwitch}>{(['MP','BR'] as const).map(m=><Pressable key={m} onPress={()=>setMode(m)} style={[s.modeBtn,mode===m&&s.modeOn]} accessibilityRole="button" accessibilityState={{selected:mode===m}}><Text style={[s.modeText,mode===m&&s.modeTextOn]}>{m==='MP'?'MULTIPLAYER':'BATTLE ROYALE'}</Text></Pressable>)}</View>
<SectionHeader title="CENTRAL RANKING" action="VIEW ALL" onAction={()=>open('RANKINGS')}/><Card accent><View style={s.rankHero}><View><Text style={s.rankLabel}>AFRICA {mode}</Text><Text style={s.rankOne}>{top?`#${top.rank} ${top.entity_name}`:liveRanks? 'NO RANKED TEAM YET':`#1 ${data[0].team}`}</Text><Text style={s.rankSub}>{top?`${top.rating} rating • ${top.matches_played} verified matches`:liveRanks?'Rankings appear after verified results':`${data[0].rating} rating • ${data[0].country}`}</Text></View><Pill text={syncState==='live'?'SYNCED':syncState==='loading'?'SYNCING':'DEMO'} tone={syncState==='live'?'green':syncState==='loading'?'blue':'gold'}/></View><View style={s.metricRow}><Metric value={(top?.matches_played??1284).toLocaleString()} label="VERIFIED MATCHES"/><Metric value={(liveRanks?.length??186).toLocaleString()} label="RANKED TEAMS"/><Metric value={(liveEvents?.length??42).toLocaleString()} label="EVENTS"/></View></Card>
{syncState==='fallback'?<Text style={s.syncNote}>API unavailable — showing the bundled showcase data.</Text>:null}
<SectionHeader title="TOURNAMENT HUB" action="HOST EVENT" onAction={()=>open('TOURNAMENT_CONTROL')}/>{cards.length?cards.map(t=><Pressable key={t.id} onPress={()=>open('TOURNAMENT_CONTROL')} style={s.event} accessibilityRole="button"><View style={s.eventTop}><View style={{flexDirection:'row',gap:6}}><Pill text={t.tier} tone={t.tier==='MAJOR'?'red':'dark'}/><Pill text={t.status} tone={t.status==='LIVE'?'green':'dark'}/></View><Text style={s.date}>{t.date}</Text></View><Text style={s.eventName}>{t.name}</Text><Text style={s.eventMeta}>{t.organizer} • {t.teams} teams • Weight {t.weight}</Text><View style={s.eventBottom}><Text style={s.prize}>{t.prize}</Text><Text style={s.link}>CONTROL CENTRE →</Text></View></Pressable>):<Card><Text style={s.emptyTitle}>No {mode} tournaments published</Text><Text style={s.emptyCopy}>Approved organizers can publish the next event from Tournament Control.</Text></Card>}
<SectionHeader title="MATCH CENTRE" action="OPEN" onAction={()=>open('MATCH_CENTRE')}/><Card><Text style={s.smallLabel}>NEXT OFFICIAL MATCH</Text><Text style={s.matchTitle}>NIM ESPORTS  vs  RAVEN ESPORTS</Text><Text style={s.matchMeta}>AER Weekly 33 • Semi Final • 20:00 WAT</Text><View style={s.actions}><ActionButton label="MATCH ROOM" onPress={()=>open('MATCH_CENTRE')}/><ActionButton label="SCRIM FINDER" secondary onPress={()=>open('SCRIM_FINDER')}/></View></Card>
</ScrollView>}
const s=StyleSheet.create({content:{padding:16,paddingBottom:32},kicker:{color:colors.redBright,fontSize:9,fontWeight:'600',letterSpacing:2},title:{color:colors.white,fontSize:24,fontWeight:'700',marginTop:4},copy:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:5,marginBottom:15},modeSwitch:{flexDirection:'row',padding:4,borderRadius:11,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,marginBottom:19},modeBtn:{flex:1,alignItems:'center',paddingVertical:10,borderRadius:8},modeOn:{backgroundColor:colors.red},modeText:{color:colors.muted,fontSize:9,fontWeight:'600'},modeTextOn:{color:'#fff'},rankHero:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},rankLabel:{color:colors.redBright,fontSize:9,fontWeight:'600',letterSpacing:1.3},rankOne:{color:colors.white,fontSize:21,fontWeight:'700',marginTop:5},rankSub:{color:colors.muted,fontSize:9,marginTop:3},metricRow:{flexDirection:'row',marginTop:18},syncNote:{color:colors.warning,fontSize:9,marginBottom:8},event:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:9,padding:14,marginBottom:10},eventTop:{flexDirection:'row',justifyContent:'space-between'},date:{color:colors.muted,fontSize:9,fontWeight:'600'},eventName:{color:colors.white,fontSize:15,fontWeight:'700',marginTop:12},eventMeta:{color:colors.muted,fontSize:9,marginTop:4},eventBottom:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:14},prize:{color:colors.white,fontSize:11,fontWeight:'600'},link:{color:colors.redBright,fontSize:8,fontWeight:'700'},emptyTitle:{color:colors.white,fontSize:13,fontWeight:'700'},emptyCopy:{color:colors.muted,fontSize:9,lineHeight:14,marginTop:5},smallLabel:{color:colors.subtle,fontSize:8,fontWeight:'600',letterSpacing:1},matchTitle:{color:colors.white,fontSize:14,fontWeight:'700',marginTop:8},matchMeta:{color:colors.muted,fontSize:9,marginTop:4},actions:{flexDirection:'row',gap:8,marginTop:14}});
