import React from 'react';
import { ScrollView,View,Text,StyleSheet,Pressable } from 'react-native';
import { colors } from '../theme/colors';
import { SectionHeader,Pill,Card } from '../components/UI';
import { DetailRoute } from '../types/navigation';
import { scrims,freeAgents } from '../data/appData';
export function HubScreen({open}:{open:(r:DetailRoute)=>void}){return <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
<Text style={s.title}>Operations</Text><Text style={s.copy}>Find scrims, scout talent, run tryouts and manage the competitive day-to-day without leaving the app.</Text>
<SectionHeader title="SCRIM FINDER" action="VIEW ALL" onAction={()=>open('SCRIM_FINDER')}/>{scrims.slice(0,2).map(x=><Pressable key={x.team} onPress={()=>open('SCRIM_FINDER')} style={s.scrim}><View style={s.scrimTop}><Text style={s.team}>{x.team}</Text><View style={{flexDirection:'row',gap:5}}><Pill text={x.tier}/><Pill text={x.mode} tone="dark"/></View></View><Text style={s.meta}>{x.region} • {x.format} • {x.time}</Text><Text style={s.maps}>{x.maps}</Text><View style={s.need}><Text style={s.needLabel}>LOOKING FOR</Text><Text style={s.needText}>{x.need}</Text><Text style={s.chat}>CHAT / WHATSAPP →</Text></View></Pressable>)}
<SectionHeader title="FREE AGENT MARKET" action="SCOUT" onAction={()=>open('FREE_AGENTS')}/><Card>{freeAgents.map((p,i)=><Pressable key={p.shid} onPress={()=>open('PLAYER_PASSPORT')} style={[s.playerRow,i<freeAgents.length-1&&s.border]}><View style={s.avatar}><Text style={s.avatarT}>{p.name[0]}</Text></View><View style={{flex:1}}><Text style={s.playerName}>{p.name}</Text><Text style={s.playerMeta}>{p.role} • {p.mode} • {p.country}</Text></View><Pill text={p.tier}/><View style={{alignItems:'flex-end'}}><Text style={s.form}>{p.form}</Text><Text style={s.val}>{p.value}</Text></View></Pressable>)}</Card>
<SectionHeader title="OPERATIONS"/><View style={s.grid}>{[['TRYOUTS','Structured trial pipelines','TRYOUTS'],['SCOUTING CENTRE','Private watchlists & notes','SCOUTING'],['TRAINING','Drills & development','PERFORMANCE'],['CALENDAR','Matches, locks & deadlines','CALENDAR'],['CONTRACT CENTRE','Deals, loans & expiries','CONTRACTS'],['ORG HQ','Roster, staff & roles','ORGANIZATION']].map(([a,b,r])=><Pressable key={a} onPress={()=>open(r as DetailRoute)} style={s.tile}><Text style={s.tileIcon}>◆</Text><Text style={s.tileTitle}>{a}</Text><Text style={s.tileSub}>{b}</Text></Pressable>)}</View>
</ScrollView>}
const s=StyleSheet.create({content:{padding:16,paddingBottom:32},kicker:{color:colors.redBright,fontSize:9,fontWeight:'600',letterSpacing:2},title:{color:colors.white,fontSize:24,fontWeight:'700',marginTop:4},copy:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:5,marginBottom:18},scrim:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:9,padding:14,marginBottom:9},scrimTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},team:{color:colors.white,fontSize:13,fontWeight:'700'},meta:{color:colors.muted,fontSize:9,marginTop:7},maps:{color:colors.white,fontSize:9,fontWeight:'600',marginTop:5},need:{marginTop:12,paddingTop:10,borderTopWidth:1,borderTopColor:'#1E1E22',flexDirection:'row',alignItems:'center',gap:7},needLabel:{color:colors.subtle,fontSize:7,fontWeight:'600'},needText:{color:colors.white,fontSize:9,fontWeight:'600'},chat:{marginLeft:'auto',color:colors.redBright,fontSize:8,fontWeight:'700'},playerRow:{minHeight:58,flexDirection:'row',alignItems:'center',gap:9},border:{borderBottomWidth:1,borderBottomColor:'#1E1E22'},avatar:{width:34,height:34,borderRadius:9,backgroundColor:colors.redSoft,alignItems:'center',justifyContent:'center'},avatarT:{color:colors.redBright,fontWeight:'700'},playerName:{color:colors.white,fontSize:10,fontWeight:'700'},playerMeta:{color:colors.muted,fontSize:8,marginTop:2},form:{color:colors.success,fontSize:10,fontWeight:'700'},val:{color:colors.muted,fontSize:8,marginTop:2},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},tile:{width:'48.5%',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:9,padding:13,minHeight:105},tileIcon:{color:colors.redBright,fontSize:16},tileTitle:{color:colors.white,fontSize:10,fontWeight:'700',marginTop:11},tileSub:{color:colors.muted,fontSize:8,lineHeight:12,marginTop:4}});
