import React from 'react';
import { ScrollView,View,Text,StyleSheet,Pressable } from 'react-native';
import { colors } from '../theme/colors';
import { DetailRoute } from '../types/navigation';
const sections:[string,[string,string,string][]][]=[
 ['PERFORMANCE',[['AI Coach','Weekly performance intelligence','PERFORMANCE'],['AI Training','Adaptive drills built from matches + VOD','AI_TRAINING'],['AI VOD Review','Review decisions & recurring mistakes','PERFORMANCE'],['Team Chemistry','Best lineups and role balance','PERFORMANCE'],['Strategy Room','Private setups and opponent prep','PERFORMANCE']]],
 ['MEDIA & COMMUNITY',[['News Feed','Transfers, results and scene news','NEWS'],['Streamer Hub','Creators, live links and rankings','STREAMERS'],['Clip System','Highlights linked to careers','MEDIA'],['Awards','Monthly and annual recognition','AWARDS']]],
 ['COMPETITIVE NETWORK',[['Connection Check','Ping, speed and Nigerian ISP intelligence','CONNECTION_CHECK'],['Rankings','MP, BR, regional and player tables','RANKINGS'],['Hall of Fame','Preserve competitive history','HALL_OF_FAME'],['Rivalries','Head-to-head and historic meetings','RIVALRIES'],['Esports Calendar','Matches, locks and deadlines','CALENDAR'],['Fantasy Esports','Tournament-specific fantasy leagues','FANTASY']]],
 ['ORGANIZATION',[['Manage Organization','Owner controls: rosters, staff, applications and schedule','ORGANIZATION'],['Contract Centre','Contracts, loans and renewals','CONTRACTS'],['Reputation','Trust, reviews and conduct','ORGANIZATION'],['Verification','Multi-badge verification system','ORGANIZATION']]],
 ['PLATFORM',[['Admin Control Centre','Approvals, disputes and system health','ADMIN'],['Notifications','Smart competitive alerts','NOTIFICATIONS'],['Public API','Approved public ecosystem data','PUBLIC_API'],['Tournament Control','Host and manage complete events','TOURNAMENT_CONTROL']]],
];
export function MoreScreen({open}:{open:(r:DetailRoute)=>void}){return <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><Text style={s.title}>More</Text><Text style={s.copy}>The full competitive ecosystem connected to one identity and one official data layer.</Text>{sections.map(([title,items])=><View key={title} style={s.section}><Text style={s.sectionTitle}>{title}</Text>{items.map(([name,sub,route],i)=><Pressable key={name} onPress={()=>open(route as DetailRoute)} style={[s.row,i<items.length-1&&s.border]}><View style={s.icon}><Text style={s.iconT}>◆</Text></View><View style={{flex:1}}><Text style={s.rowTitle}>{name}</Text><Text style={s.rowSub}>{sub}</Text></View><Text style={s.chev}>›</Text></Pressable>)}</View>)}</ScrollView>}
const s=StyleSheet.create({content:{padding:16,paddingBottom:32},kicker:{color:colors.redBright,fontSize:9,fontWeight:'600',letterSpacing:2},title:{color:colors.white,fontSize:24,fontWeight:'700',marginTop:4},copy:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:5,marginBottom:18},section:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:9,overflow:'hidden',marginBottom:12},sectionTitle:{color:colors.subtle,fontSize:8,fontWeight:'700',letterSpacing:1.3,paddingHorizontal:13,paddingTop:12,paddingBottom:7},row:{minHeight:61,flexDirection:'row',alignItems:'center',paddingHorizontal:12,gap:10},border:{borderBottomWidth:1,borderBottomColor:'#1E1E22'},icon:{width:31,height:31,borderRadius:8,backgroundColor:colors.redSoft,alignItems:'center',justifyContent:'center'},iconT:{color:colors.redBright,fontWeight:'700'},rowTitle:{color:colors.white,fontSize:10,fontWeight:'700'},rowSub:{color:colors.muted,fontSize:8,marginTop:3},chev:{color:colors.muted,fontSize:20}});
