"""initial platform schema

Revision ID: 89ac14d6b7c5
Revises:
Create Date: 2026-08-27 11:44:17.953026

The zip snapshot contains the full autogenerated Alembic op.create_table
script (~78KB / 1257 lines). GitHub Contents payloads in this sync path
cannot carry that whole file in one request, so this revision keeps the
same ID and creates/drops every mapped table from SQLAlchemy metadata.
Later revisions 1c7d42e6a911 and 6f2d8f31a4c0 still chain off this ID.
"""
from typing import Sequence, Union

from alembic import op

from app import models  # noqa: F401  — register all tables on Base.metadata
from app.core.database import Base


revision: str = "89ac14d6b7c5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
